webext-perms-description-bookmarks = Read and modify bookmarks
webext-perms-description-browserSettings = Read and modify browser settings
webext-perms-description-browsingData = Clear recent browsing history, cookies, and related data
webext-perms-description-clipboardRead = Get data from the clipboard
webext-perms-description-clipboardWrite = Input data to the clipboard
webext-perms-description-declarativeNetRequest = Block content on any page
webext-perms-description-declarativeNetRequestFeedback = Read your browsing history
webext-perms-description-devtools = Extend developer tools to access your data in open tabs
webext-perms-description-downloads = Download files and read and modify the browser’s download history
webext-perms-description-downloads-open = Open files downloaded to your computer
webext-perms-description-find = Read the text of all open tabs
webext-perms-description-geolocation = Access your location
webext-perms-description-history = Access browsing history
webext-perms-description-management = Monitor extension usage and manage themes
webext-perms-description-nativeMessaging = Exchange messages with programs other than Thunderbird
webext-perms-description-notifications = Display notifications to you
webext-perms-description-pkcs = Provide cryptographic authentication services
webext-perms-description-privacy = Read and modify privacy settings
webext-perms-description-proxy = Control browser proxy settings
webext-perms-description-sessions = Access recently closed tabs
webext-perms-description-tabs = Access browser tabs
webext-perms-description-tabHide = Hide and show browser tabs
webext-perms-description-topSites = Access browsing history
webext-perms-description-trialML = Download and run AI models on your device
webext-perms-description-userScripts = Allow unverified third-party scripts to access your data
webext-perms-description-webNavigation = Access browser activity during navigation
webext-perms-description-data-short-authenticationInfo = authentication information
webext-perms-description-data-short-bookmarksInfo = bookmarks
webext-perms-description-data-short-browsingActivity = browsing activity
webext-perms-description-data-short-financialAndPaymentInfo = financial and payment information
webext-perms-description-data-short-healthInfo = health information
webext-perms-description-data-short-locationInfo = location
webext-perms-description-data-short-personalCommunications = personal communications
webext-perms-description-data-short-personallyIdentifyingInfo = personally identifying information
webext-perms-description-data-short-searchTerms = search terms
webext-perms-description-data-short-technicalAndInteraction = technical and interaction data
webext-perms-description-data-short-websiteActivity = website activity
webext-perms-description-data-short-websiteContent = website content
webext-perms-description-data-long-authenticationInfo = Share authentication information with extension developer
webext-perms-description-data-long-bookmarksInfo = Share bookmarks information with extension developer
webext-perms-description-data-long-browsingActivity = Share browsing activity with extension developer
webext-perms-description-data-long-financialAndPaymentInfo = Share financial and payment information with extension developer
webext-perms-description-data-long-healthInfo = Share health information with extension developer
webext-perms-description-data-long-locationInfo = Share location information with extension developer
webext-perms-description-data-long-personalCommunications = Share personal communications with extension developer
webext-perms-description-data-long-personallyIdentifyingInfo = Share personally identifying information with extension developer
webext-perms-description-data-long-searchTerms = Share search terms with extension developer
webext-perms-description-data-long-technicalAndInteraction = Share technical and interaction data with extension developer
webext-perms-description-data-long-websiteActivity = Share website activity with extension developer
webext-perms-description-data-long-websiteContent = Share website content with extension developer
webext-perms-description-accountsFolders = Create, rename, or delete your mail account folders
webext-perms-description-accountsIdentities = Create, modify or delete your mail account identities
webext-perms-description-accountsRead = See your mail accounts, their identities and their folders
webext-perms-description-addressBooks = Read and modify your address books and contacts
webext-perms-description-compose = Read and modify your email messages as you compose and send them
webext-perms-description-compose-send = Send composed email messages on your behalf
webext-perms-description-compose-save = Save composed email messages as drafts or templates
webext-perms-description-experiment-access = This add-on will have have full, unrestricted access to Thunderbird, and your computer.
webext-perms-description-messagesImport = Import messages into Thunderbird
webext-perms-description-messagesModify = Read and modify your email messages as they are displayed to you
webext-perms-description-messagesModifyPermanent = Permanently modify the source of your messages (including headers, body and attachments)
webext-perms-description-messagesMove = Copy or move your email messages (including moving them to the trash folder)
webext-perms-description-messagesDelete = Permanently delete your email messages
webext-perms-description-messagesRead = Read your email messages
webext-perms-description-messagesUpdate = Change properties and tags of your email messages
webext-perms-description-messagesTags = Create, modify and delete message tags
webext-perms-description-messagesTagsList = List message tags
webext-perms-description-sensitiveDataUpload = Transfer sensitive user data (if access has been granted) to a remote server for further processing
webext-perms-description-messengerSettings = Read Thunderbird settings
